#!/bin/sh

trackid=$(playerctl metadata mpris:trackid)

if [[ "$trackid" == *"org/ncspot"* ]]; then
    artist=$(playerctl metadata xesam:artist)
    title=$(playerctl metadata xesam:title)
    echo "<span color='#ffffff' >$artist </span>- $title "
    exit 0
fi
